channels:
  - pytorch
dependencies:
  - python=3.10.6
  - pip:
    - ruff
    - pprintpp~=0.4.0
    - python-dotenv~=1.0.0
    - jsonpatch==1.32
    - matplotlib==3.7.3
    - seaborn~=0.12.1
    - pandas~=1.5.3
    - evaluate==0.4.1
    - trectools==0.0.49